const LOGIN_SUCCESS = 'SIGNIN_SUCCESS'
const ERROR_MSG = 'ERROR_MSG'
const LOG_OUT = 'SING_UP'
const REGISTER = 'REGISTER'
const GET_PRODUCTS = 'GET_PRODUCTS'
const PURCHASE = 'PURCHASE'
export { LOGIN_SUCCESS, ERROR_MSG, LOG_OUT, REGISTER, GET_PRODUCTS, PURCHASE }
